    # depends_on:
    #   - write-home-timeline-rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: compose-post-service
  labels:
    death-star-project: social-network
    app: compose-post-service
  namespace: ai4cloudops-11855c
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app: compose-post-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compose-post-service
  labels:
    death-star-project: social-network
    app: compose-post-service
  namespace: ai4cloudops-11855c
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: compose-post-service
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: compose-post-service
      name: compose-post-service
    spec:
      containers:
      - name: compose-post-service
        image: rohankumar1/social-network-microservices:latest
        imagePullPolicy: Always
        command: ["ComposePostService", "sh ./install_packages.sh"]
        volumeMounts:
          - mountPath: /social-network-microservices/config/jaeger-config.yml
            subPath: jaeger-config.yml
            name: jaeger-conf-yaml
          - mountPath: /social-network-microservices/config/service-config.json
            subPath: service-config.json
            name: service-config-json
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 2000m
        #     memory: 500Mi

      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
        - name: jaeger-conf-yaml
          configMap:
            name: jaeger-config-yaml
        - name: service-config-json
          configMap:
            name: service-config-json
