---
apiVersion: v1
kind: Service
metadata:
  name: compose-post-redis
  labels:
    death-star-project: social-network
    app: compose-post-redis
  namespace: ai4cloudops-11855c
spec:
  ports:
  - port: 6379
  selector:
    death-star-project: social-network
    app: compose-post-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compose-post-redis
  labels:
    death-star-project: social-network
    app: compose-post-redis
  namespace: ai4cloudops-11855c
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: compose-post-redis
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: compose-post-redis
      name: compose-post-redis
    spec:
      containers:
      - name: compose-post-redis
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 500Mi

      restartPolicy: Always

      imagePullSecrets:
        - name: regcred
