---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-docker-client
  labels:
    death-star-project: social-network
    app: docker-docker-client
  namespace: ai4cloudops-11855c
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: docker-client
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: docker-client
      name: docker-client
    spec:
      containers:
      - name: docker-client
        image: docker
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 500Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0

        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: Always
#          - apt-get -y update &&
#            apt-get -y upgrade &&
#            apt-get -y install dnsutils git vim python3 python3-aiohttp libssl-dev libz-dev luarocks iputils-ping lynx build-essential gcc bash curl &&
#            luarocks install luasocket &&
#            sleep 365d
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred2

