---
apiVersion: v1
kind: Service
metadata:
  name: home-timeline-service
  labels:
    death-star-project: social-network
    app: home-timeline-service
  namespace: ai4cloudops-11855c
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app: home-timeline-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-timeline-service
  labels:
    death-star-project: social-network
    app: home-timeline-service
  namespace: ai4cloudops-11855c
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: home-timeline-service
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: home-timeline-service
      name: home-timeline-service
    spec:
      containers:
      - name: home-timeline-service
        image: rohankumar1/social-network-microservices:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 500Mi
        command: ["HomeTimelineService", "sh ./install_packages.sh"]
        volumeMounts:
          - mountPath: /social-network-microservices/config/jaeger-config.yml
            subPath: jaeger-config.yml
            name: jaeger-conf-yaml
          - mountPath: /social-network-microservices/config/service-config.json
            subPath: service-config.json
            name: service-config-json

      restartPolicy: Always
      imagePullSecrets:
        - name: regcred2
      volumes:
        - name: jaeger-conf-yaml
          configMap:
            name: jaeger-config-yaml
        - name: service-config-json
          configMap:
            name: service-config-json
