---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-out
  labels:
    death-star-project: social-network
    app-name: jaeger
  namespace: ai4cloudops-f7f10d9
spec:
  type: NodePort
  ports:
  - port: 16686
  selector:
    death-star-project: social-network
    app-name: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  labels:
    death-star-project: social-network
    app-name: jaeger
  namespace: ai4cloudops-f7f10d9
spec:
  ports:
  - port: 5775
    name: udp1
    protocol: UDP
  - port: 5778
    name: tcp1
  - port: 6831
    name: udp2
    protocol: UDP
  - port: 6832
    name: udp3
    protocol: UDP
  - port: 14250
    name: tcp2
  - port: 14268
    name: tcp3
  selector:
    death-star-project: social-network
    app-name: jaeger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-agent
  labels:
    death-star-project: social-network
    app-name: jaeger
  namespace: ai4cloudops-f7f10d9
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: jaeger
  template:
    metadata:
      labels:
        death-star-project: social-network
        app-name: jaeger
      name: jaeger-agent
    spec:
      containers:
      - name: jaeger-agent
        image: jaegertracing/all-in-one:1.46
        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        - name: JAEGER_AGENT_PORT
          value: "5775"
        resources:
          requests:
            memory: "4Gi"   # Request 4 gibibytes of memory
            cpu: "2"      # Request 2 CPU cores
          limits:
            memory: "8Gi"   # Limit to 8 gibibytes of memory
            cpu: "4"        # Limit to 4 CPU core

      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
