---
apiVersion: v1
kind: Service
metadata:
  name: text-service
  labels:
    death-star-project: social-network
    app: text-service
  namespace: ai4cloudops-f7f10d9
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app: text-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-service
  labels:
    death-star-project: social-network
    app: text-service
  namespace: ai4cloudops-f7f10d9
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: text-service
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: text-service
      name: text-service
    spec:
      containers:
      - name: text-service
        image: smqasim/social-network-microservices:latest
        command: ["TextService"]
        volumeMounts:
          - mountPath: /social-network-microservices/config/jaeger-config.yml
            subPath: jaeger-config.yml
            name: jaeger-conf-yaml
      restartPolicy: Always
      volumes:
        - name: jaeger-conf-yaml
          configMap:
            name: jaeger-config-yaml
