---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-server
  namespace: ai4cloudops-f7f10d9
  labels:
    death-star-project: media-microsvc
    app: nginx-web-server
spec:
  type: NodePort
  ports:
  - port: 8180
  selector:
    death-star-project: media-microsvc
    app: nginx-web-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-server
  namespace: ai4cloudops-f7f10d9
  labels:
    death-star-project: media-microsvc
    app: nginx-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: media-microsvc
      app: nginx-web-server
  template:
    metadata:
      labels: 
        death-star-project: media-microsvc
        app: nginx-web-server
      name: nginx-web-server
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: nginx-web-server
        image: smqasim/openresty-thrift:xenial-media
        ports:
          - containerPort: 8180
        imagePullPolicy: Always
      restartPolicy: Always
