version: "3.9"
services:
  social-graph-service:
    image: smqasim/social-network-microservices:latest
    # hostname: social-graph-service
    #    ports:
    #      - 10000:9090
    cpus: 1
    mem_limit: 1G
    depends_on:
      jaeger-agent:
        condition: service_started
      social-graph-mongodb:
        condition: service_started
    restart: always
    entrypoint: SocialGraphService
    volumes:
      - ./config:/social-network-microservices/config
      - /local/astraea-spans:/astraea-spans

  social-graph-mongodb:
    image: mongo
    cpus: 1
    mem_limit: 1G
    # hostname: social-graph-mongodb
    # ports:
    #   - 27018:27017
    restart: always

  social-graph-redis:
    image: redis
    cpus: 1
    mem_limit: 1G
    # hostname: social-graph-redis
    # ports:
    #   - 6380:6379
    restart: always

  home-timeline-redis:
    image: redis
    cpus: 1
    mem_limit: 1G
    # hostname: home-timeline-redis
    # ports:
    #   - 6381:6379
    restart: always

  compose-post-service:
    image: sqasim/social-network-microservices:latest
    cpus: 1
    mem_limit: 1G
    # hostname: compose-post-service
    #    ports:
    #      - 10001:9090
    restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
    entrypoint: ComposePostService
    volumes:
      - ./config:/social-network-microservices/config
      - /local/astraea-spans:/astraea-spans

  post-storage-service:
    image: mert/social-network-microservices:latest
    # hostname: post-storage-service
    cpus: 1
    mem_limit: 1G
    ports:
      - 10002:9090
    restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
      post-storage-mongodb:
        condition: service_started
    entrypoint: PostStorageService
    volumes:
      - ./config:/social-network-microservices/config
      - /local/astraea-spans:/astraea-spans

  post-storage-memcached:
    image: memcached
    cpus: 1
    mem_limit: 1G
    # hostname: post-storage-memcached
    #    ports:
    #      - 11212:11211
    restart: always

  post-storage-mongodb:
    image: mongo
    cpus: 1
    mem_limit: 1G
    # hostname: post-storage-mongodb
    #    ports:
    #      - 27019:27017
    restart: always

  user-timeline-service:
    image: mert/social-network-microservices:latest
    # hostname: user-timeline-service
    #    ports:
    #      - 10003:9090
    cpus: 1
    mem_limit: 1G
    restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
      user-timeline-mongodb:
        condition: service_started
    entrypoint: UserTimelineService
    volumes:
      - ./config:/social-network-microservices/config
      - /local/astraea-spans:/astraea-spans

  user-timeline-redis:
    image: redis
    cpus: 1
    mem_limit: 1G
    # hostname: user-timeline-redis
    #    ports:
    #      - 6383:6379
    restart: always

  user-timeline-mongodb:
    image: mongo
    cpus: 1
    mem_limit: 1G
    # hostname: user-timeline-mongodb
    #    ports:
    #      - 27020:27017
    restart: always

  url-shorten-service:
    image: mert/social-network-microservices:latest
    cpus: 1
    mem_limit: 1G
    # hostname: url-shorten-service
    #    ports:
    #      - 10004:9090
    restart: always
    entrypoint: UrlShortenService
    depends_on:
      jaeger-agent:
        condition: service_started
      url-shorten-mongodb:
        condition: service_started
    volumes:
      - ./config:/social-network-microservices/config
      - /local/astraea-spans:/astraea-spans

  url-shorten-memcached:
    image: memcached
    cpus: 1
    mem_limit: 1G
    # hostname: url-shorten-memcached
    #    ports:
    #      - 11213:11211
    restart: always

  url-shorten-mongodb:
    image: mongo
    cpus: 1
    mem_limit: 1G
    # hostname: url-shorten-mongodb
    #    ports:
    #      - 27021:27017
    restart: always

  user-service:
    image: mert/social-network-microservices:latest
    cpus: 1
    mem_limit: 1G
    # hostname: user-service
    #    ports:
    #      - 10005:9090
    restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
      user-mongodb:
        condition: service_started
    entrypoint: UserService
    volumes:
      - ./config:/social-network-microservices/config
      - /local/astraea-spans:/astraea-spans

  user-memcached:
    image: memcached
    cpus: 1
    mem_limit: 1G
    # hostname: user-memcached
    #    ports:
    #      - 11214:11211
    restart: always

  user-mongodb:
    image: mongo
    cpus: 1
    mem_limit: 1G
    # hostname: user-mongodb
    # ports:
    #   - 27023:27017
    restart: always

  media-service:
    image: mert/social-network-microservices:latest
    cpus: 1
    mem_limit: 1G
    # hostname: media-service
    #    ports:
    #      - 10006:9090
    depends_on:
      jaeger-agent:
        condition: service_started
      media-mongodb:
        condition: service_started
    restart: always
    entrypoint: MediaService
    volumes:
      - ./config:/social-network-microservices/config
      - /local/astraea-spans:/astraea-spans

  media-memcached:
    image: memcached
    cpus: 1
    mem_limit: 1G
    # hostname: media-memcached
    #    ports:
    #      - 11215:11211
    restart: always

  media-mongodb:
    image: mongo
    cpus: 1
    mem_limit: 1G
    # hostname: media-mongodb
    #    ports:
    #      - 27024:27017
    restart: always

  text-service:
    image: mert/social-network-microservices:latest
    cpus: 1
    mem_limit: 1G
    # hostname: text-service
    #    ports:
    #      - 10007:9090
    restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
    entrypoint: TextService
    volumes:
      - ./config:/social-network-microservices/config
      - /local/astraea-spans:/astraea-spans

  unique-id-service:
    image: mert/social-network-microservices:latest
    cpus: 1
    mem_limit: 1G
    # hostname: unique-id-service
    #    ports:
    #      - 10008:9090
    restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
    entrypoint: UniqueIdService
    volumes:
      - ./config:/social-network-microservices/config
      - /local/astraea-spans:/astraea-spans

  user-mention-service:
    image: mert/social-network-microservices:latest
    cpus: 1
    mem_limit: 1G
    # hostname: user-mention-service
    #    ports:
    #      - 10009:9090
    depends_on:
      jaeger-agent:
        condition: service_started
    restart: always
    entrypoint: UserMentionService
    volumes:
      - ./config:/social-network-microservices/config
      - /local/astraea-spans:/astraea-spans

  home-timeline-service:
    image: mert/social-network-microservices:latest
    cpus: 1
    mem_limit: 1G
    # hostname: home-timeline-service
    #    ports:
    #      - 10010:9090
    depends_on:
      jaeger-agent:
        condition: service_started
    restart: always
    entrypoint: HomeTimelineService
    volumes:
      - ./config:/social-network-microservices/config
      - /local/astraea-spans:/astraea-spans

  nginx-thrift:
    image: yg397/openresty-thrift:xenial
    cpus: 2
    mem_limit: 2G
    # hostname: nginx-thrift
    ports:
      - 8080:8080
    depends_on:
      jaeger-agent:
        condition: service_started
    restart: always
    volumes:
      - ./nginx-web-server/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./nginx-web-server/pages:/usr/local/openresty/nginx/pages
      - ./nginx-web-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx-web-server/jaeger-config.json:/usr/local/openresty/nginx/jaeger-config.json
      - ./gen-lua:/gen-lua
      - ./docker/openresty-thrift/lua-thrift:/usr/local/openresty/lualib/thrift

  media-frontend:
    image: yg397/media-frontend:xenial
    # hostname: media-frontend
    cpus: 1
    mem_limit: 1G
    ports:
      - 8081:8080
    restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
    volumes:
      - ./media-frontend/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./media-frontend/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf

  jaeger-agent:
    image: jaegertracing/all-in-one:latest
    ports:
      #      - 5775:5775/udp
      #      - 6831:6831/udp
      #      - 6832:6832/udp
      #      - 5778:5778
      - 16686:16686
      #      - 14268:14268
      #      - 9411:9411
    restart: always
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
