version: "3"
services:
#   Enables resolving container hostnames from host machine
  dns-media:
    image: defreitas/dns-proxy-server
    volumes:
      - /opt/dns-proxy-server/conf:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf

  unique-id-service:
    image: smqasim/media-microservices:latest
    hostname: unique-id-service
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 10001:9090
    restart: always
    entrypoint: UniqueIdService
    volumes:
      - /local/astraea-spans:/astraea-spans

  movie-id-service:
    image: smqasim/media-microservices:latest
    hostname: movie-id-service
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 10002:9090
    restart: always
    entrypoint: MovieIdService
    volumes:
      - /local/astraea-spans:/astraea-spans

  movie-id-mongodb:
    image: mongo
    hostname: movie-id-mongodb
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 27018:27017
    restart: always

  movie-id-memcached:
    image: memcached
    hostname: movie-id-memcached
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 11212:11211
    restart: always

  text-service:
    image: smqasim/media-microservices:latest
    hostname: text-service
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 10003:9090
    restart: always
    entrypoint: TextService
    volumes:
      - /local/astraea-spans:/astraea-spans

  rating-service:
    image: smqasim/media-microservices:latest
    hostname: rating-service
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 10004:9090
    restart: always
    entrypoint: RatingService
    volumes:
      - /local/astraea-spans:/astraea-spans

  rating-redis:
    image: redis
    hostname: rating-redis
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 6382:6379
    restart: always

  user-service:
    image: smqasim/media-microservices:latest
    hostname: user-service
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 10005:9090
    restart: always
    entrypoint: UserService
    volumes:
      - /local/astraea-spans:/astraea-spans

  user-mongodb:
    image: mongo
    hostname: user-mongodb
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 27019:27017
    restart: always

  user-memcached:
    image: memcached
    hostname: user-memcached
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 11213:11211
    restart: always

  compose-review-service:
    image: smqasim/media-microservices:latest
    hostname: compose-review-service
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 10006:9090
    restart: always
    entrypoint: ComposeReviewService
    volumes:
      - /local/astraea-spans:/astraea-spans

  compose-review-memcached:
    image: memcached
    hostname: compose-review-memcached
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 11214:11211
    restart: always

  review-storage-service:
    image: smqasim/media-microservices:latest
    hostname: review-storage-service
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 10007:9090
    restart: always
    entrypoint: ReviewStorageService
    volumes:
      - /local/astraea-spans:/astraea-spans

  review-storage-mongodb:
    image: mongo
    hostname: review-storage-mongodb
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 27020:27017
    restart: always

  review-storage-memcached:
    image: memcached
    hostname: review-storage-memcached
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 11215:11211
    restart: always

  user-review-service:
    image: smqasim/media-microservices:latest
    hostname: user-review-service
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 10008:9090
    restart: always
    entrypoint: UserReviewService
    volumes:
      - /local/astraea-spans:/astraea-spans

  user-review-mongodb:
    image: mongo
    hostname: user-review-mongodb
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 27021:27017
    restart: always

  user-review-redis:
    image: redis
    hostname: user-review-redis
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 6381:6379
    restart: always

  movie-review-service:
    image: smqasim/media-microservices:latest
    hostname: movie-review-service
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 10009:9090
    restart: always
    entrypoint: MovieReviewService
    volumes:
      - /local/astraea-spans:/astraea-spans

  movie-review-mongodb:
    image: mongo
    hostname: movie-review-mongodb
    cpus: 1
    mem_limit: 1G
    ports:
      - 27022:27017
    restart: always

  movie-review-redis:
    image: redis
    hostname: movie-review-redis
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 6380:6379
    restart: always

  nginx-web-server:
    image: yg397/openresty-thrift:xenial
    hostname: nginx-thrift
    cpus: 2
    mem_limit: 2G
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./nginx-web-server/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./nginx-web-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx-web-server/jaeger-config.json:/usr/local/openresty/nginx/jaeger-config.json
      - ./gen-lua:/gen-lua

  cast-info-service:
    image: smqasim/media-microservices:latest
    hostname: cast-info-service
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 10010:9090
    restart: always
    entrypoint: CastInfoService
    volumes:
      - /local/astraea-spans:/astraea-spans

  cast-info-mongodb:
    image: mongo
    hostname: cast-info-mongodb
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 27024:27017
    restart: always

  cast-info-memcached:
    image: memcached
    hostname: cast-info-memcached
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 11219:11211
    restart: always

  plot-service:
    image: smqasim/media-microservices:latest
    hostname: plot-service
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 10011:9090
    restart: always
    entrypoint: PlotService
    volumes:
      - /local/astraea-spans:/astraea-spans

  plot-mongodb:
    image: mongo
    hostname: plot-mongodb
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 27025:27017
    restart: always

  plot-memcached:
    image: memcached
    hostname: plot-memcached
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 11220:11211
    restart: always

  movie-info-service:
    image: smqasim/media-microservices:latest
    hostname: movie-info-service
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 10012:9090
    restart: always
    entrypoint: MovieInfoService
    volumes:
      - /local/astraea-spans:/astraea-spans

  movie-info-mongodb:
    image: mongo
    hostname: movie-info-mongodb
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 27026:27017
    restart: always

  movie-info-memcached:
    image: memcached
    hostname: movie-info-memcached
    cpus: 1
    mem_limit: 1G
#    ports:
#      - 11221:11211
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    hostname: jaeger
    ports:
#      - 5775:5775/udp
#      - 6831:6831/udp
#      - 6832:6832/udp
#      - 5778:5778
      - 16686:16686
#      - 14268:14268
#      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
